APP_NAME = "AdminForge"
APP_VERSION = "0.1.0"
APP_AUTHOR = "Furkan Kane"

WINDOW_TITLE = f"{APP_NAME} v{APP_VERSION}"
WINDOW_WIDTH = 1400
WINDOW_HEIGHT = 900

COMPANY_NAME = "AdminForge"
APP_SIGNATURE = "ADMINFORGE_CORE"